### ISSUE TITLE
thanks for using Ott-jax!

### ISSUE THREAD

**Issue by marcocuturi** [EddieCunningham/generax#1]
In this line there is a (minor) silent bug:

https://github.com/EddieCunningham/generax/blob/b672f51ef2a1f6c2bba80678b60551244670dd7c/generax/distributions/coupling.py#L89

essentially this should be either 

```
# Create a sinkhorn solver
solver = sinkhorn.Sinkhorn()

# Solve the OT problem
ot = solver(ot_prob)
```

or you could do this as ```ot = sinkhorn.Sinkhorn()(ot_prob)```

the reason this is silent is that the first parameter to create a solver is `lse_mode`, which is a bool. When tested, in our code, as in `if lse_mode: ...` essentially this returns to True.

**Comment by EddieCunningham** [comment]
Thanks for all of the work in jax-ott and for catching this bug!  I've just pushed a fix for this.
